version: '3'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
      - ./solr-config-linux:/opt/solr/server/solr/configsets/solr-config
      - ./solr-config-linux:/var/solr/data/configsets/solr-config
      
    command: ["solr", "-f", "create_core", "-c", "v2"]
    networks:
      - mi-red-docker

volumes:
  data:

networks:
  mi-red-docker:
    external: true
